### ISSUE TITLE
Some new wallpapers

### ISSUE THREAD

**Issue by MechDR** [oSoWoSo/Void-Wallpapers#1]
Here are some new wallpapers :).
![void001](https://github.com/oSoWoSo/Void-Wallpapers/assets/45944962/e3793209-01fd-4873-a06c-09ffce371c50)
![void002](https://github.com/oSoWoSo/Void-Wallpapers/assets/45944962/8f44a7f8-742a-4451-a2fb-358694d1fa6f)

**Comment by zen0bit** [comment]
why not create PR instead?

**Comment by MechDR** [comment]
OK 👍.
